//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelVacationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Departments = new HashSet<Department>();
            this.Employee1 = new HashSet<Employee>();
            this.requests = new HashSet<request>();
        }
    
        public int emp_ssn { get; set; }
        public string name { get; set; }
        public string Email { get; set; }
        public Nullable<int> mgr_ssn { get; set; }
        public Nullable<int> Dno { get; set; }
        public int isManager { get; set; }
        public Nullable<decimal> Casual_vacation { get; set; }
        public Nullable<decimal> Regular_vacation { get; set; }
        public decimal Total_Available_days { get; set; }
        public bool Social_insurance { get; set; }
        public Nullable<System.DateTime> Hiring_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request> requests { get; set; }
    }
    public enum isManager
    {
        Employee = 0,
        Manager
    }
    public struct convertEnum
    {
        public int value { get; set; }
        public string name { get; set; }
    }
}
