//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelVacationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int empID { get; set; }
        public int vacID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> approval { get; set; }
        public string empName { get; set; }


        public virtual Employee Employee { get; set; }
        public virtual vacation vacation { get; set; }
    }
}
